const TARGET=new Date("2027-07-03T00:00:00+05:30");
const CREATOR="chitra-creator-2027", CKEY="chitra_creator_v3", MKEY="chitra_mode_v3", VKEY="chitra_visited_v3";
const rooms=[
["garden","01 · Luminous Garden","Grow a private constellation with your clicks."],
["letters","02 · The Unsent Library","Letters for feelings that never fit into ordinary messages."],
["poetry","03 · Velvet Words","Original English and Hinglish poetry, written for this sky."],
["memory","04 · Museum of Small Things","Tiny memories that become enormous when remembered."],
["timeline","05 · Tomorrow, Unwritten","A future told without pretending to know it."],
["signals","06 · Seven Quiet Signals","A hidden transmission for curious explorers."],
["dream","07 · Dream Weather","Change the emotional weather of the world."],
["observatory","08 · The Faraway Room","A place for stars, perspective and silence."],
["modes","09 · Four Different Skies","Four atmospheres, each changing the whole world."],
["finale","10 · Where the Sky Opens","The birthday room. Sealed until the date."]
];
const creator=new URLSearchParams(location.search).get("creator")==="1"||sessionStorage.getItem(CKEY)==="yes";
const birthday=()=>Date.now()>=TARGET.getTime();
const allowed=()=>creator||birthday();
const main=document.getElementById("main"),drawer=document.getElementById("drawer"),toast=document.getElementById("toast");
function msg(x){toast.textContent=x;toast.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.remove("show"),2200)}
function mode(m){document.body.dataset.mode=m;localStorage.setItem(MKEY,m);document.getElementById("modeName").textContent=m.toUpperCase();document.querySelectorAll("[data-mode]").forEach(x=>x.setAttribute("aria-current",x.dataset.mode===m));}
mode(localStorage.getItem(MKEY)||"aurora");
document.getElementById("modeChip").onclick=()=>{const a=["aurora","moon","rose","midnight"],i=a.indexOf(localStorage.getItem(MKEY)||"aurora");mode(a[(i+1)%a.length]);msg("Atmosphere: "+a[(i+1)%a.length])};
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{mode(b.dataset.mode);closeDrawer();msg("Atmosphere changed.")});
document.getElementById("menuBtn").onclick=()=>drawer.classList.add("open");
document.getElementById("closeDrawer").onclick=closeDrawer;
function closeDrawer(){drawer.classList.remove("open")}
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
rooms.forEach(r=>{const b=document.createElement("button");b.dataset.route=r[0];b.innerHTML=esc(r[1])+"<small>"+esc(r[2])+"</small>";document.getElementById("nav").appendChild(b)});

function home(){let open=birthday();return `<section class="page"><div class="wrap"><div class="hero-grid"><div>
<div class="kicker">03 · JULY · 2027 / ${open?"THE DOORS ARE OPEN":"COUNTING THE DISTANCE"}</div>
<h1>CHITRA.<span>A sky written for you.</span></h1>
<p class="lede">This is not a webpage you are supposed to finish. It is a place you are supposed to wander through. I wanted your birthday to have rooms instead of a single screen, little secrets instead of a single message, and enough quiet corners for you to discover something when you least expect it.</p>
${open?`<div class="quote">The waiting is over. Take your time. The universe has been holding the lights on for you.</div>`:
`<div class="count"><div class="c"><div class="num" id="d">--</div><div class="unit">days</div></div><div class="c"><div class="num" id="h">--</div><div class="unit">hours</div></div><div class="c"><div class="num" id="m">--</div><div class="unit">minutes</div></div><div class="c"><div class="num" id="s">--</div><div class="unit">seconds</div></div></div>`}
<div class="tiny">${open?"TODAY, EVERY DOOR IS YOURS.":"MIDNIGHT · 03 JULY 2027 · INDIA STANDARD TIME"}</div>
<div class="deep">If I could give you one thing that would never expire, I would give you <em>proof that you mattered on an ordinary day.</em> Not because you achieved something. Not because you were perfect. Simply because you were here. So this little world exists — not to measure you, fix you, or ask anything from you, but to leave a small light somewhere that says: <em>your existence has been worth celebrating.</em></div>
<div class="buttons">${open?`<button class="primary" data-route="garden">OPEN THE FIRST DOOR →</button>`:`<button class="primary" data-route="poetry">READ SOMETHING WHILE YOU WAIT →</button>`}${!open?`<button class="secondary" id="creator">CREATOR PREVIEW</button>`:""}</div>
<div class="tiny" style="margin-top:18px">Explore: <span id="progress">0%</span> · The menu contains every room.</div>
</div><aside class="note"><span class="kicker">A LETTER BEFORE THE COUNTDOWN ENDS</span><h3>Some gifts are objects. Some are places.</h3><p>Imagine opening a gift and finding no object inside it — only a door. Behind that door is another door, and behind that one a garden, and somewhere in the garden is a sentence you did not know you needed today.</p><p>That is the idea here. A slow birthday. A little world. No pressure to understand it all.</p><p>And yes, there are things hidden in it. Because ordinary birthday wishes are lovely, but curiosity deserves a seat at the table too.</p></aside></div></div></section>`}
function room(title,no,body){return `<section class="page"><div class="room"><button class="back" data-route="home">← BACK TO SKY</button><div class="room-head"><div class="kicker">ROOM ${no} · CHITRA ARCHIVE</div><h2>${title}</h2></div>${body}</div></section>`}
function garden(){return room("Luminous Garden","01",`<p class="longread">The garden begins empty because every beautiful thing deserves a beginning. Plant lights. Watch the stems appear. There is no score, only evidence that you stopped long enough to leave something behind.</p><div class="interactive"><canvas id="garden" class="garden"></canvas><div class="meter"><i id="gm"></i></div><button class="primary" id="plant">PLANT A LIGHT</button> <button class="secondary" id="sleep">CLEAR THE GARDEN</button><p id="gt" class="signal"></p></div>`)}
function letters(){return room("The Unsent Library","02",`<article class="letter"><span class="kicker">LETTER 01 · TO THE GIRL WHO KEEPS GOING</span><h3>Dear Chitra,</h3><p>There will be days when you feel like you are behind everyone else. Please remember that life is not a classroom where every person is supposed to reach the same chapter on the same morning. You are allowed to take the long way. You are allowed to change your mind. You are allowed to become someone your younger self could not have imagined.</p><p>I hope you meet people who make you feel safe enough to be ridiculous. People with whom silence is not awkward, laughter is not performed, and affection does not come with a bill attached.</p></article><article class="letter"><span class="kicker">LETTER 02 · FOR THE DAYS THAT FEEL HEAVY</span><h3>Keep breathing.</h3><p>Not every difficult season needs a dramatic lesson. Sometimes you simply survive it. That is enough. You do not have to turn every wound into wisdom before you are allowed to rest.</p><p>And if one day you look back and realise you became softer rather than harder, I hope you count that as a victory.</p></article><article class="letter"><span class="kicker">LETTER 03 · THE SIMPLEST ONE</span><h3>Hey Chitra,</h3><p>This entire place exists because “happy birthday” felt too short. So I made the sentence longer. Much longer. Probably unnecessarily longer. But some people make you want to spend the extra time.</p><p>May your life contain more moments that make you forget to check the time.</p></article>`)}
function poetry(){return room("Velvet Words","03",`<div class="poem"><p>Maybe you were never meant to be</p><p>a chapter I could finish.</p><p>Maybe you were the little pause</p><p>that taught the sentence to breathe.</p><p>────────</p><p>You came quietly,</p><p>like moonlight under a closed door,</p><p>and somehow the room looked different</p><p>without you touching a thing.</p><p>────────</p><p>Some names are not written</p><p>to be owned by a story.</p><p>Some are written simply</p><p>so the story remembers it was beautiful.</p></div><div class="quote">Hinglish — “Kuch log zindagi mein rukne ke liye nahi aate. Woh bas itna kar jaate hain ki unke jaane ke baad bhi dil ke kisi kone mein ek chhoti si roshni jalti rehti hai.”</div><div class="longread">Chitra, agar yaadein letters hoti na, toh tumhare naam wale envelope ko main kabhi seal nahi karta. Usme woh saari chhoti chhoti baatein rakhta jo us waqt important nahi lagti thi — random laughs, pointless conversations, woh moments jinke paas koi grand meaning nahi tha.

Because maybe that is what makes a life beautiful.

Not the huge cinematic scenes.

The tiny ones.

The “sun rahi ho?” messages. The accidental jokes. The sudden comfort. The conversation that was supposed to last five minutes and somehow became an hour. The ordinary afternoon that only becomes precious years later.

Aur shayad isi liye birthday bhi sirf ek date nahi hota. It is proof that one ordinary day, years ago, the world quietly made room for one more person.

That person was you.</div>`)}
function memory(){return room("Museum of Small Things","04",`<div class="cards"><div class="card"><span class="kicker">EXHIBIT A</span><h3>The Random Laugh</h3><p>The kind that starts from something stupid and refuses to stop. No historical importance. Maximum emotional value.</p></div><div class="card"><span class="kicker">EXHIBIT B</span><h3>The Ordinary Day</h3><p>Most memories do not look like memories while they are happening. They look like Tuesday.</p></div><div class="card"><span class="kicker">EXHIBIT C</span><h3>The Little Things</h3><p>A phrase, a song, a screenshot, a nickname, a tiny moment. The things we almost throw away become the things we later wish we could hold.</p></div></div><div class="quote">One day, you will miss a version of today that you did not realise was worth remembering.</div>`)}
function timeline(){return room("Tomorrow, Unwritten","05",`<div class="cards"><div class="card"><span class="kicker">SOMEDAY</span><h3>A morning you haven't lived</h3><p>Sunlight, a new song, a different routine, and a version of you who already knows that the worry you have today did not last forever.</p></div><div class="card"><span class="kicker">NO DATE</span><h3>An unreasonable laugh</h3><p>One day something unbelievably stupid will make you laugh until your stomach hurts. I hope you remember that happiness does not need a sophisticated reason.</p></div><div class="card"><span class="kicker">FUTURE NOTE</span><h3>A softer chapter</h3><p>Not perfect. Not painless. Just softer. A chapter where you stop apologising for needing peace.</p></div></div><div class="longread" style="margin-top:32px">The future is not a promise that everything will be easy. It is simply the fact that there are pages you have not read yet.

So do not judge your entire story from a difficult paragraph.

Keep going.</div>`)}
function signals(){return room("Seven Quiet Signals","06",`<p class="longread">There are seven transmissions. Press the receiver slowly. The final message only appears when all seven have been heard.</p><div class="interactive"><button class="primary" id="signal">RECEIVE TRANSMISSION</button><p id="sc" class="signal">0 / 7 · waiting for curiosity</p><div id="so" class="longread" style="display:none;margin-top:22px">TRANSMISSION COMPLETE.<br><br>“If you ever feel lost, remember that lost is a location, not an identity. You can leave a location.”</div></div>`)}
function dream(){return room("Dream Weather","07",`<div class="interactive"><span class="kicker">EMOTIONAL WEATHER ENGINE</span><h3 id="dt" style="font:500 48px var(--serif);margin:10px 0">Choose a feeling.</h3><p id="db" class="longread">The room changes its words when you change the weather.</p><div class="buttons"><button class="secondary feel" data-f="calm">CALM</button><button class="secondary feel" data-f="wild">WILD</button><button class="secondary feel" data-f="hope">HOPE</button><button class="secondary feel" data-f="nostalgia">NOSTALGIA</button></div></div><div class="quote" id="dq">A quiet universe is still a universe.</div>`)}
function observatory(){return room("The Faraway Room","08",`<div class="cards"><div class="card"><span class="kicker">STAR 01</span><h3>Distance</h3><p>Light can spend years travelling before someone sees it. Some kindness works the same way.</p></div><div class="card"><span class="kicker">STAR 02</span><h3>Perspective</h3><p>From far enough away, a problem becomes a point of light. It remains real, but breathing becomes easier.</p></div><div class="card"><span class="kicker">STAR 03</span><h3>Wonder</h3><p>You are allowed to care about things that have no practical purpose. Wonder does not need to justify itself.</p></div></div><div class="quote">Look at the sky sometimes without asking it for an answer.</div>`)}
function modes(){return room("Four Different Skies","09",`<p class="longread">Every mode changes the entire atmosphere, not just a button colour. Pick one. Stay. Then switch. Notice how the same words feel different under different weather.</p><div class="cards"><div class="card"><span class="kicker">AURORA</span><h3>Wonder</h3><p>Violet and teal. The feeling of finding something beautiful when you were not searching.</p><button class="secondary sm" data-set="aurora">ENTER</button></div><div class="card"><span class="kicker">MOON</span><h3>Quiet</h3><p>Blue night. A slower room for slower thoughts.</p><button class="secondary sm" data-set="moon">ENTER</button></div><div class="card"><span class="kicker">ROSE</span><h3>Warmth</h3><p>Pink and amber. The colour of memories that still feel gentle.</p><button class="secondary sm" data-set="rose">ENTER</button></div></div><div class="card" style="margin-top:12px"><span class="kicker">MIDNIGHT</span><h3>Depth</h3><p>Electric cyan against deep space. The hidden side of the archive.</p><button class="secondary sm" data-set="midnight">ENTER</button></div>`)}
function finale(){return room("Where the Sky Opens","10",`<div class="final"><span class="kicker">${birthday()?"03 · 07 · 2027 · OPEN":"SEALED UNTIL 03 · 07 · 2027"}</span><h2>${birthday()?"Happy Birthday, Chitra.":"Not yet."}</h2>${birthday()?`<div class="poem"><p>May your mornings find you gently.</p><p>May your nights leave room for stars.</p><p>May you never confuse being needed with being loved.</p><p>May you keep your softness without mistaking it for weakness.</p><p>May laughter find you in ordinary places.</p><p>May the future surprise you kindly.</p></div><div class="longread">Chitra, this strange little universe was built around a simple thought: a birthday can be a pause. A chance to look at what survived, what exists now, and what might still become.

I hope you collect years that feel like rooms with open windows.

I hope you meet people who do not make you earn your place beside them.

I hope you keep the parts of yourself that make no practical sense.

And when life becomes loud, I hope you remember that there is always a quieter sky inside you.

Happy birthday.

The website ends here.

The universe doesn't.</div>`:`<div class="quote">This door is deliberately quiet. When July 3, 2027 arrives, it will stop asking permission.</div>`}</div>`)}
const pages={home,garden,letters,poetry,memory,timeline,signals,dream,observatory,modes,finale};
function render(){let key=location.hash.slice(1)||"home";if(!pages[key])key="home";if(!allowed()&&key!=="home"&&key!=="poetry"){msg("This room is waiting for July 3, 2027.");key="home"}main.innerHTML=pages[key]();bind(key);progress(key);tick()}
function bind(key){
document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>{location.hash=b.dataset.route;closeDrawer();scrollTo(0,0)});
const c=document.getElementById("creator");if(c)c.onclick=()=>{let p=prompt("Creator preview code");if(p===CREATOR){sessionStorage.setItem(CKEY,"yes");msg("Creator preview unlocked.");render()}else msg("The code did not open the archive.")};
document.querySelectorAll(".sm").forEach(b=>b.onclick=()=>{mode(b.dataset.set);msg("Atmosphere: "+b.dataset.set)});
if(key==="garden"){const c=document.getElementById("garden"),x=c.getContext("2d");function size(){c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);draw()}function draw(){x.clearRect(0,0,c.clientWidth,c.clientHeight);let n=+localStorage.garden||0;x.lineWidth=1;for(let i=0;i<n;i++){let px=(i*71)%c.clientWidth,py=c.clientHeight-20-(i*29)%(c.clientHeight-45);x.strokeStyle=getComputedStyle(document.body).getPropertyValue("--a");x.beginPath();x.moveTo(px,py);x.lineTo(px+(i%3-1)*13,py-55-(i%4)*9);x.stroke();x.fillStyle=getComputedStyle(document.body).getPropertyValue("--b");x.beginPath();x.arc(px+(i%3-1)*13,py-55-(i%4)*9,3+(i%3),0,7);x.fill()}}function upd(){let n=+localStorage.garden||0;document.getElementById("gm").style.width=Math.min(100,n*4)+"%";document.getElementById("gt").textContent=n?"The garden remembers that you stopped here.":"The soil is waiting for its first light.";draw()}document.getElementById("plant").onclick=()=>{localStorage.garden=(+localStorage.garden||0)+1;upd();msg("A light found its place.")};document.getElementById("sleep").onclick=()=>{localStorage.garden=0;upd();msg("The garden is sleeping.")};addEventListener("resize",size);size();upd()}
if(key==="signals"){let n=0;document.getElementById("signal").onclick=()=>{n++;document.getElementById("sc").textContent=n+" / 7 · signal received";if(n>=7){document.getElementById("so").style.display="block";msg("The seventh signal arrived.")}}}
if(key==="dream"){const d={calm:["The room exhales.","Nothing needs to be solved tonight.","Let quiet be enough."],wild:["Be a little unreasonable.","Take the long road for no reason.","Some joy is supposed to be impractical."],hope:["There are unopened mornings.","There are people you haven't met yet.","The story is still moving."],nostalgia:["The past can be beautiful without becoming a destination.","Keep the warmth.","Release the weight."]};document.querySelectorAll(".feel").forEach(b=>b.onclick=()=>{let a=d[b.dataset.f];document.getElementById("dt").textContent=a[0];document.getElementById("db").textContent=a[1];document.getElementById("dq").textContent=a[2]})}}
function progress(key){let v=JSON.parse(localStorage.getItem(VKEY)||"[]");if(key!=="home"&&!v.includes(key)){v.push(key);localStorage.setItem(VKEY,JSON.stringify(v))}let p=document.getElementById("progress");if(p)p.textContent=Math.min(100,Math.round(v.length/rooms.length*100))+"%"}
function tick(){let diff=Math.max(0,TARGET-Date.now());let vals=[Math.floor(diff/86400000),Math.floor(diff/3600000)%24,Math.floor(diff/60000)%60,Math.floor(diff/1000)%60];["d","h","m","s"].forEach((id,i)=>{let e=document.getElementById(id);if(e)e.textContent=String(vals[i]).padStart(2,"0")})}
setInterval(()=>{if(document.getElementById("d"))tick();if(birthday()&&!creator&&location.hash==="#home")render()},1000);
addEventListener("hashchange",render);render();

/* Background is independent from all page content */
const sky=document.getElementById("sky"),ctx=sky.getContext("2d");let stars=[];
function resize(){sky.width=innerWidth*devicePixelRatio;sky.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);stars=Array.from({length:Math.min(240,Math.floor(innerWidth/5))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.2+Math.random()*1.5,a:.12+Math.random()*.75,v:.03+Math.random()*.2}))}
function starsLoop(){ctx.clearRect(0,0,innerWidth,innerHeight);let col=getComputedStyle(document.body).getPropertyValue("--a");for(const s of stars){s.y+=s.v;if(s.y>innerHeight)s.y=-2;ctx.globalAlpha=s.a;ctx.fillStyle=col;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill()}ctx.globalAlpha=1;requestAnimationFrame(starsLoop)}
addEventListener("resize",resize);resize();starsLoop();
