const target=new Date('2027-07-03T00:00:00+05:30');
const app=document.querySelector('#main'), nav=document.querySelector('#nav'), menu=document.querySelector('#menu'), toast=document.querySelector('#toast');
const rooms=[['garden','The Living Garden','Grow a constellation with every click.'],['letters','Letters Never Sent','Three letters, three versions of the same feeling.'],['poetry','Poetry Room','English, Hinglish, and the words that sit between.'],['memory','Memory Vault','A quiet archive of tiny things worth keeping.'],['timeline','The Unwritten Timeline','A timeline of moments that never needed to be famous.'],['signals','Signal Station','Decode the little messages hidden in the universe.'],['dream','Dream Lab','Choose a feeling and watch the world mutate.'],['observatory','Observatory','Look outward until the universe becomes personal.'],['finale','The Last Door','The room that should only feel complete on July 3.']];
const isBirthday=()=>{const n=new Date();return n>=target && n.getFullYear()===2027 && n.getMonth()===6 && n.getDate()===3};
let creator=sessionStorage.getItem('chitraCreator')==='yes';
function unlocked(){return creator||isBirthday()||new Date()>=target}
function countdown(){const el=id=>document.getElementById(id); if(!el('d'))return; const diff=Math.max(0,target-new Date()); const d=Math.floor(diff/864e5),h=Math.floor(diff/36e5)%24,m=Math.floor(diff/6e4)%60,s=Math.floor(diff/1e3)%60; el('d').textContent=String(d).padStart(2,'0');el('h').textContent=String(h).padStart(2,'0');el('m').textContent=String(m).padStart(2,'0');el('s').textContent=String(s).padStart(2,'0'); if(unlocked()) location.hash='home'} setInterval(countdown,1000);
function save(k,v){localStorage.setItem(k,v)} function get(k,d=''){return localStorage.getItem(k)||d}
function home(){const publicNow=unlocked(); app.innerHTML=`<section class="page"><div class="hero"><div class="kicker">03 · 07 · 2027 / ${publicNow?'THE DOORS ARE OPEN':'THE UNIVERSE IS STILL LOADING'}</div><h1>CHITRA.<span>A universe written in light.</span></h1><p class="lede">This is not a birthday page. It is a place built slowly — one room at a time — for one person who deserves to find a little wonder waiting for her.</p>${!publicNow?`<div class="count"><div class="cell"><div class="num" id="d">--</div><div class="lab">days</div></div><div class="cell"><div class="num" id="h">--</div><div class="lab">hours</div></div><div class="cell"><div class="num" id="m">--</div><div class="lab">minutes</div></div><div class="cell"><div class="num" id="s">--</div><div class="lab">seconds</div></div></div><div class="notice">The doors open automatically at midnight, July 3, 2027 · IST.</div>`:`<div class="quote">“Some places are visited. Some are remembered. This one was made to be discovered.”</div>`}<div class="actions">${publicNow?'<button class="primary" data-go="garden">ENTER THE UNIVERSE →</button>':'<button class="primary" data-go="garden">PEEK INSIDE →</button>'}<button class="secondary" id="creatorBtn">${creator?'CREATOR MODE ON':'CREATOR PREVIEW'}</button></div><div class="meta-row"><span>made for <strong>Chitra</strong></span><span>exploration <strong id="explore">0%</strong></span><span>mode <strong>${document.body.dataset.mode.toUpperCase()}</strong></span></div><div class="footer-note">No algorithm knows why this exists. That is the point.</div></div></section>`; countdown(); document.querySelector('#creatorBtn').onclick=()=>creatorPrompt();}
function creatorPrompt(){if(creator){creator=false;sessionStorage.removeItem('chitraCreator');toastMsg('Creator preview locked.');render();return}const x=prompt('Creator access code');if(x==='chitra-creator-2027'){creator=true;sessionStorage.setItem('chitraCreator','yes');toastMsg('Creator preview unlocked.');render()}else if(x!==null)toastMsg('That key did not open the door.');}
function poetry(){return `<section class="page"><div class="room"><button class="back" data-go="home">← BACK TO THE THRESHOLD</button><div class="room-head"><div class="kicker">room 03 / words</div><h2>Poetry Room</h2><p>For the things that are too soft to say loudly, and too important to leave unsaid.</p></div><article class="poem"><p>Maybe some people arrive like rain —</p><p>not to change the sky,</p><p>but to make you notice</p><p>you had been looking at it all along.</p><p>And maybe, Chitra,</p><p>you are one of those people.</p></article><article class="longread">There are people you meet and immediately understand. Then there are people you understand slowly, in fragments — through a random conversation, an unexpected laugh, a sentence they almost didn't send, a silence that somehow says more than a paragraph ever could. You belong to the second kind of story.

I wanted this place to feel like that. Not loud. Not desperate to impress. Just quietly strange enough that, while exploring it, you occasionally stop and think, “Wait… someone actually made this?”

Because birthdays are usually measured in candles, photographs, messages, and a number getting larger every year. But a person is much bigger than a date. A person is the collection of tiny moments nobody else saw. The songs that stayed. The jokes that made no sense. The nights that felt longer than they should. The versions of yourself you outgrew without even announcing it.

So this is my little attempt at preserving the feeling instead of merely wishing the day.

Happy birthday, Chitra. May the next chapter be softer where it needs to be, louder where you want it to be, and completely yours where nobody else gets to decide what it should look like.</article><div class="sig">— written in a corner of the internet, for you.</div></div></section>`}
function letters(){return `<section class="page"><div class="room"><button class="back" data-go="home">← BACK</button><div class="room-head"><div class="kicker">room 02 / archive</div><h2>Letters Never Sent</h2><p>Three letters from three different versions of the same night.</p></div><div class="cards"><div class="card"><div class="kicker">01 / ordinary</div><h3>Dear Chitra,</h3><p>I hope today gives you one completely unnecessary reason to smile. Not because you have to be happy all the time, but because sometimes life accidentally leaves a beautiful little thing in your path.</p></div><div class="card"><div class="kicker">02 / midnight</div><h3>2:17 AM</h3><p>If you ever feel like you are behind, remember that life is not a race with one finish line. Some flowers bloom early. Some bloom after everyone stopped checking.</p></div><div class="card"><div class="kicker">03 / future</div><h3>From later.</h3><p>You will become someone your current self cannot completely imagine. I hope you meet her gently. I hope she knows how hard you worked to get there.</p></div></div><p class="quote">“You don't have to become someone else to deserve a beautiful life.”</p></div></section>`}
function garden(){return `<section class="page"><div class="room"><button class="back" data-go="home">← BACK</button><div class="room-head"><div class="kicker">room 01 / generative</div><h2>The Living Garden</h2><p>Every click plants a light. Nothing is pre-drawn. The garden remembers what you grow.</p></div><div class="terminal" id="gardenOut">$ garden.boot()<br><span>initialising soil...</span><br><span>waiting for a seed.</span></div><div class="actions"><button class="primary" id="seed">PLANT A SEED ✦</button><button class="secondary" id="clearSeed">LET THE NIGHT REST</button></div><div class="progress"><i id="gardenProgress"></i></div></div></section>`}
function memory(){return `<section class="page"><div class="room"><button class="back" data-go="home">← BACK</button><div class="room-head"><div class="kicker">room 04 / fragments</div><h2>Memory Vault</h2><p>Not every memory needs a photograph. Some only need a sentence.</p></div><div class="cards"><div class="card"><div class="kicker">fragment 001</div><h3>The small things</h3><p>Someone remembered your favorite thing. Someone waited. Someone sent a message just because they saw something that reminded them of you.</p></div><div class="card"><div class="kicker">fragment 002</div><h3>The laugh</h3><p>There are laughs that are polite, laughs that are automatic, and the dangerous ones — the ones that make your stomach hurt because you forgot to stop.</p></div><div class="card"><div class="kicker">fragment 003</div><h3>Keep going</h3><p>Some chapters end without becoming meaningless. The fact that something ended does not erase the fact that it once mattered.</p></div></div><p class="quote">Archive the good. Learn from the difficult. Keep moving.</p></div></section>`}
function timeline(){return `<section class="page"><div class="room"><button class="back" data-go="home">← BACK</button><div class="room-head"><div class="kicker">room 05 / time</div><h2>The Unwritten Timeline</h2><p>A timeline does not need exact dates. Sometimes it only needs feelings.</p></div><div class="cards"><div class="card"><div class="kicker">before</div><h3>Unknown</h3><p>Two lives moving independently, collecting their own weather, stories, mistakes, songs and strange little victories.</p></div><div class="card"><div class="kicker">then</div><h3>A hello</h3><p>One ordinary interaction quietly becomes part of the archive. Nothing announces itself as important while it is happening.</p></div><div class="card"><div class="kicker">now</div><h3>This room</h3><p>A birthday becomes an excuse to build something ridiculous, over-engineered and completely unnecessary — which is precisely why it is worth building.</p></div><div class="card"><div class="kicker">next</div><h3>Unknown</h3><p>The best part of a timeline is the blank space. It means there are still things neither of us has seen.</p></div></div></div></section>`}
function signals(){return `<section class="page"><div class="room"><button class="back" data-go="home">← BACK</button><div class="room-head"><div class="kicker">room 06 / hidden frequency</div><h2>Signal Station</h2><p>Some messages are easier to find when they are disguised as nonsense.</p></div><div class="terminal" id="signal"><span>signal://CHITRA</span><br>frequency ........ 03.07<br>packet ........... 001101<br>origin ........... somewhere warm<br>status ........... waiting<br><br><span>hint: click the line below exactly seven times.</span><br><button id="signalBtn" style="background:none;color:#a8f5e8;padding:0;font:inherit">&gt; receive()</button></div><p id="signalText" class="quote" style="display:none">You found it. The universe was never hiding a secret. It was hiding an excuse to make you look closer.</p></div></section>`}
function dream(){return `<section class="page"><div class="room"><button class="back" data-go="home">← BACK</button><div class="room-head"><div class="kicker">room 07 / mutable reality</div><h2>Dream Lab</h2><p>Choose a word. The background will remember it for the rest of your visit.</p></div><div class="actions"><button class="secondary dreamBtn">CALM</button><button class="secondary dreamBtn">WILD</button><button class="secondary dreamBtn">HOPE</button><button class="secondary dreamBtn">NOSTALGIA</button></div><div class="quote" id="dreamQuote">A quiet universe is still a universe.</div><div class="longread">The strange thing about dreams is that they rarely explain themselves. They simply show up with impossible architecture, familiar faces, doors where walls should be, oceans inside bedrooms and skies that behave like mirrors.

Maybe websites can do the same. Maybe a page doesn't have to behave like a document. Maybe it can feel like a place.

That is what this room is trying to become.</div></div></section>`}
function observatory(){return `<section class="page"><div class="room"><button class="back" data-go="home">← BACK</button><div class="room-head"><div class="kicker">room 08 / looking outward</div><h2>Observatory</h2><p>Look at the stars long enough and scale becomes a funny concept.</p></div><div class="cards"><div class="card"><div class="kicker">star 01</div><h3>Distance</h3><p>Light can spend years travelling before reaching a place where someone finally sees it.</p></div><div class="card"><div class="kicker">star 02</div><h3>Perspective</h3><p>From far enough away, entire problems become points of light. It does not make them unreal. It makes room for breathing.</p></div><div class="card"><div class="kicker">star 03</div><h3>Wonder</h3><p>Never underestimate the usefulness of being curious about something that has no practical purpose.</p></div></div><p class="quote">Somewhere between “too much” and “not enough” is a life that is simply yours.</p></div></section>`}
function finale(){return `<section class="page"><div class="room"><button class="back" data-go="home">← BACK</button><div class="room-head"><div class="kicker">final room / 03 july</div><h2>The Last Door</h2><p>This room changes on the birthday. Before then, it is a promise. On the day, it becomes the ending.</p></div><article class="poem"><p>For Chitra —</p><p>May your mornings find you kindly,</p><p>may your nights leave room for stars,</p><p>may the people who enter your life</p><p>know the difference between holding on</p><p>and holding you back.</p><p>May you laugh without checking who is listening.</p><p>May you leave rooms that make you smaller.</p><p>May you keep the parts of yourself</p><p>that the world once asked you to hide.</p><p>And when the future feels enormous,</p><p>take it one ordinary day at a time.</p></article><article class="longread">If you reached the last door, then you have officially spent far too much time exploring a website that should probably have been a simple “Happy Birthday!” page.

Good.

That was the point.

I wanted you to have somewhere to wander. Somewhere that did not ask you to reply immediately, smile on command, or understand everything at once. A place where you could click around, get lost, discover a hidden sentence, change the sky, plant a tiny light, read something at an unreasonable length and eventually arrive here.

Because sometimes the gift is not the object. Sometimes the gift is the amount of thought someone was willing to spend making a moment feel different.

So here is the simplest line on the entire website:

Happy Birthday, Chitra.

I hope this year gives you more reasons to stay curious, more people who make you feel safe being completely yourself, more ridiculous laughter, more peaceful mornings, and fewer moments where you have to convince yourself that you are enough.

You already are.

The rest is just exploration.</article><div class="sig">03 · 07 · 2027 / the universe is yours to explore.</div></div></section>`}
function render(){let key=(location.hash.slice(1)||'home').split('?')[0]; if(key!=='home'&&!rooms.some(r=>r[0]===key))key='home'; if(!unlocked()&&key!=='home'&&key!=='garden'&&key!=='poetry'){toastMsg('This door is waiting for July 3, 2027. Creator Preview can open it early.');key='home'} const pages={home, garden, poetry, letters, memory, timeline, signals, dream, observatory, finale};pages[key](); updateExplore(); bind();}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.go;closeDrawer()}); if(document.querySelector('#seed')){let count=+get('seeds','0'); const out=document.querySelector('#gardenOut'), prog=document.querySelector('#gardenProgress');const paint=()=>{prog.style.width=Math.min(100,count*10)+'%';out.innerHTML='$ garden.boot()<br><span>seeds planted: '+count+'</span><br><span>'+(['a tiny green point','a second light appears','something is beginning','the garden remembers you','the sky has roots now'][Math.min(4,Math.floor(count/2))])+'</span>';};document.querySelector('#seed').onclick=()=>{count++;save('seeds',count);paint();toastMsg('A new light appeared.');};document.querySelector('#clearSeed').onclick=()=>{count=0;save('seeds','0');paint()};paint()} if(document.querySelector('#signalBtn')){let n=0;document.querySelector('#signalBtn').onclick=()=>{n++;if(n>=7){document.querySelector('#signalText').style.display='block';save('signal','found');toastMsg('Signal received.')}}}document.querySelectorAll('.dreamBtn').forEach(b=>b.onclick=()=>{const v=b.textContent.toLowerCase();document.querySelector('#dreamQuote').textContent={calm:'Breathe. The universe is not asking you to hurry.',wild:'Let the stars be loud tonight.',hope:'There are still unopened doors.',nostalgia:'Some moments become warmer when remembered.'}[v]})}
function updateExplore(){const visited=JSON.parse(get('visited','[]'));const key=(location.hash.slice(1)||'home');if(key!=='home'&&!visited.includes(key)){visited.push(key);save('visited',JSON.stringify(visited))}const el=document.querySelector('#explore');if(el)el.textContent=Math.round(visited.length/rooms.length*100)+'%'}
function toastMsg(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
rooms.forEach(r=>{const b=document.createElement('button');b.textContent=r[1];b.dataset.go=r[0];nav.appendChild(b)});
document.querySelector('#menuBtn').onclick=()=>{menu.classList.add('open');menu.setAttribute('aria-hidden','false')};document.querySelector('#closeMenu').onclick=closeDrawer;function closeDrawer(){menu.classList.remove('open');menu.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-mode-choice]').forEach(b=>b.onclick=()=>{const m=b.dataset.modeChoice;document.body.dataset.mode=m;localStorage.setItem('mode',m);document.querySelector('#modeName').textContent=m.toUpperCase();toastMsg('Mode changed to '+m+'.');closeDrawer()});document.querySelector('#modeBtn').onclick=()=>{const modes=['aurora','moon','rose','midnight'];const m=modes[(modes.indexOf(document.body.dataset.mode)+1)%modes.length];document.body.dataset.mode=m;localStorage.setItem('mode',m);document.querySelector('#modeName').textContent=m.toUpperCase();toastMsg('Mode changed to '+m+'.')};
const savedMode=get('mode','aurora');document.body.dataset.mode=savedMode;document.querySelector('#modeName').textContent=savedMode.toUpperCase();
window.addEventListener('hashchange',render);render();
// particle field
const c=document.querySelector('#space'),ctx=c.getContext('2d');let stars=[];function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);stars=Array.from({length:Math.min(180,Math.floor(innerWidth/7))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.5+.2,a:Math.random()*.7+.1,v:Math.random()*.25+.05}))}function tick(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){s.y+=s.v;if(s.y>innerHeight)s.y=0;ctx.globalAlpha=s.a;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(tick)}addEventListener('resize',resize);resize();tick();
