const target=new Date("2027-07-03T00:00:00+05:30"), PASS="chitra-creator-2027";
const rooms=[["garden","Luminous Garden","A garden that grows when you stay."],["letters","The Unsent Library","Words that never needed an envelope."],["poetry","Velvet Words","English and Hinglish, written slowly."],["memory","Museum of Small Things","The tiny things that become everything."],["timeline","Tomorrow, Unwritten","Pages the future has not filled yet."],["signals","Seven Quiet Signals","A transmission hidden in plain sight."],["dream","Dream Weather","Change the emotional weather."],["observatory","The Faraway Room","Perspective from very far away."],["modes","Four Different Skies","One world, four atmospheres."],["finale","Where the Sky Opens","The room that waits for July 3."]];
const page=document.getElementById("page"),menu=document.getElementById("menu"),toast=document.getElementById("toast");
let creator=sessionStorage.getItem("creator")==="yes"; const unlocked=()=>creator||Date.now()>=target;
function toggleMenu(){menu.classList.toggle("open")} function notify(t){toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800)}
function setMode(m){document.body.dataset.mode=m;localStorage.mode=m;notify("Atmosphere: "+m)}
setMode(localStorage.mode||"aurora");
document.getElementById("rooms").innerHTML=rooms.map((r,i)=>`<button class="roomlink" onclick="go('${r[0]}')">${String(i+1).padStart(2,"0")} · ${r[1]}<small>${r[2]}</small></button>`).join("");
function go(id){location.hash=id;menu.classList.remove("open");scrollTo(0,0)}
function wrap(title,num,body){return `<section class="page"><div class="room"><button class="back" onclick="go('home')">← BACK TO SKY</button><div class="eyebrow">ROOM ${num} · CHITRA ARCHIVE</div><h2>${title}</h2>${body}</div></section>`}
function home(){let open=Date.now()>=target;return `<section class="page"><div class="wrap hero"><div><div class="eyebrow">${open?"03 JULY 2027 · THE DOORS ARE OPEN":"COUNTING THE DISTANCE · 03 JULY 2027"}</div><h1>CHITRA.<span>A sky written for you.</span></h1><p class="lead">Some birthday wishes are sentences. This one is a place. Walk slowly. Open rooms. Change the sky. Read what you want and leave whenever you want. There is no correct way to explore it.</p>${open?`<div class="quote">The waiting is over. Every door is yours now.</div>`:`<div class="count"><div><div class="num" id="d">--</div><div class="unit">DAYS</div></div><div><div class="num" id="h">--</div><div class="unit">HOURS</div></div><div><div class="num" id="m">--</div><div class="unit">MINUTES</div></div><div><div class="num" id="s">--</div><div class="unit">SECONDS</div></div></div>`}<div class="deep">If I could give you one thing that never expires, I would give you <em>proof that your existence has been worth celebrating.</em> Not because you had to become someone extraordinary first. Simply because you are here.</div><div class="btns"><button class="primary" onclick="go('${open?"garden":"poetry"}')">${open?"ENTER THE UNIVERSE →":"READ WHILE YOU WAIT →"}</button>${!open?`<button class="secondary" onclick="preview()">CREATOR PREVIEW</button>`:""}</div></div><aside class="sidecard" style="position:static;transform:none;width:auto;max-height:none"><div class="eyebrow">A NOTE BEFORE THE DOORS OPEN</div><h3>Don't rush this place.</h3><p>It was made to take time. There are quiet rooms, interactive corners, different atmospheres and words that are meant to be read more than once.</p><p>On the birthday, the preview disappears and the archive becomes completely open.</p></aside></div></section>`}
function garden(){return wrap("Luminous Garden","01",`<p class="intro">Click to plant lights. The garden remembers your little visits in this browser.</p><div class="interactive"><canvas id="gc" class="garden"></canvas><div class="bar"><i id="gb"></i></div><button class="primary" onclick="plant()">PLANT A LIGHT</button> <button class="secondary" onclick="clearGarden()">LET IT SLEEP</button><p id="gt" class="signal"></p></div>`)}
function letters(){return wrap("The Unsent Library","02",`<article class="letter"><div class="eyebrow">LETTER 01 · FOR THE GIRL WHO KEEPS GOING</div><h3>Dear Chitra,</h3><p>There will be mornings when everyone seems ahead and you feel as if your own story forgot to move. Please do not measure your life against somebody else's timeline. You are not late. You are living a life that has never happened before.</p><p>I hope you meet people who make silence comfortable, laughter effortless, and affection feel like a home instead of a test.</p></article><article class="letter"><div class="eyebrow">LETTER 02 · FOR HEAVY DAYS</div><h3>Keep breathing.</h3><p>Not every difficult season needs to become a lesson immediately. Sometimes surviving the day is the whole achievement. Rest is not a failure of ambition. Softness is not a lack of strength.</p></article><article class="letter"><div class="eyebrow">LETTER 03 · THE SIMPLE ONE</div><h3>Hey Chitra,</h3><p>This whole universe exists because “happy birthday” felt far too short for someone who deserved more than a sentence.</p></article>`)}
function poetry(){return wrap("Velvet Words","03",`<div class="poem"><p>Maybe you were never meant to be</p><p>a chapter I could finish.</p><p>Maybe you were the little pause</p><p>that taught the sentence to breathe.</p><p>────────</p><p>You arrived quietly,</p><p>like moonlight beneath a closed door,</p><p>and somehow the room became softer.</p><p>────────</p><p>Some names are not written</p><p>to be owned by a story.</p><p>Some are written</p><p>so the story remembers it was beautiful.</p></div><div class="quote">“Kuch log zindagi mein rukne ke liye nahi aate. Woh bas itna kar jaate hain ki unke jaane ke baad bhi dil ke kisi kone mein ek chhoti si roshni jalti rehti hai.”</div><p class="long">Agar yaadein letters hoti na, toh tumhare naam wala envelope main kabhi seal nahi karta. Usme woh chhoti chhoti baatein rakhta jo us waqt ordinary lagti thi — random laughs, pointless conversations, woh moments jinke paas koi grand meaning nahi tha.

Because maybe beautiful lives are mostly made of those moments.

Not the cinematic ones.

The tiny ones.

Aur shayad birthday bhi sirf ek date nahi hota. It is proof that one ordinary day, years ago, the world quietly made room for one more person.

That person was you.</p>`)}
function memory(){return wrap("Museum of Small Things","04",`<div class="cards"><div class="card"><div class="eyebrow">EXHIBIT A</div><h3>The Random Laugh</h3><p>A ridiculous joke. A laugh that lasts too long. No historical importance. Maximum emotional value.</p></div><div class="card"><div class="eyebrow">EXHIBIT B</div><h3>The Ordinary Day</h3><p>Most memories do not look like memories while they happen. They look like Tuesday.</p></div><div class="card"><div class="eyebrow">EXHIBIT C</div><h3>The Little Thing</h3><p>A phrase, a song, a screenshot, a tiny moment. Small things become enormous when time touches them.</p></div></div><div class="quote">One day, you may miss a version of today that you never realised was worth remembering.</div>`)}
function timeline(){return wrap("Tomorrow, Unwritten","05",`<div class="cards"><div class="card"><div class="eyebrow">SOMEDAY</div><h3>A morning not yet lived</h3><p>Sunlight, a new song, a different routine, and a version of you who knows today's worry did not last forever.</p></div><div class="card"><div class="eyebrow">NO DATE</div><h3>An unreasonable laugh</h3><p>Something unbelievably stupid will make you laugh until your stomach hurts. Happiness does not need a sophisticated reason.</p></div><div class="card"><div class="eyebrow">FUTURE NOTE</div><h3>A softer chapter</h3><p>Not perfect. Not painless. Just softer. A chapter where peace no longer needs an apology.</p></div></div><p class="long">The future is not a promise that everything will be easy. It is simply the fact that there are pages you have not read yet.

So do not judge your entire story from a difficult paragraph.

Keep going.</p>`)}
function signals(){return wrap("Seven Quiet Signals","06",`<p class="intro">Seven transmissions are hidden here. Press the receiver seven times. The final message waits for the complete sequence.</p><div class="interactive"><button class="primary" onclick="signal()">RECEIVE SIGNAL</button><p id="sig" class="signal">0 / 7 · receiver quiet</p><p id="secret" class="long" style="display:none">TRANSMISSION COMPLETE.

If you ever feel lost, remember: lost is a location, not an identity. You can leave a location.</p></div>`)}
function dream(){return wrap("Dream Weather","07",`<div class="interactive"><div class="eyebrow">EMOTIONAL WEATHER ENGINE</div><h3 id="weatherTitle" style="font:500 48px var(--serif);margin:12px 0">Choose a feeling.</h3><p id="weatherBody" class="long">The room changes its words when you change the weather.</p><div class="btns"><button class="secondary" onclick="weather('calm')">CALM</button><button class="secondary" onclick="weather('wild')">WILD</button><button class="secondary" onclick="weather('hope')">HOPE</button><button class="secondary" onclick="weather('nostalgia')">NOSTALGIA</button></div></div><div class="quote" id="weatherQuote">A quiet universe is still a universe.</div>`)}
function observatory(){return wrap("The Faraway Room","08",`<div class="cards"><div class="card"><div class="eyebrow">STAR 01</div><h3>Distance</h3><p>Light can travel for years before somebody sees it. Some kindness works the same way.</p></div><div class="card"><div class="eyebrow">STAR 02</div><h3>Perspective</h3><p>From far enough away, a problem becomes a point of light. Still real, but easier to breathe beside.</p></div><div class="card"><div class="eyebrow">STAR 03</div><h3>Wonder</h3><p>You are allowed to care about beautiful things with no practical purpose.</p></div></div><div class="quote">Look at the sky sometimes without asking it for an answer.</div>`)}
function modes(){return wrap("Four Different Skies","09",`<p class="intro">The same universe feels different under different weather. Choose an atmosphere and stay long enough to notice.</p><div class="cards"><div class="card"><div class="eyebrow">AURORA</div><h3>Wonder</h3><p>Violet and teal. The feeling of finding beauty without looking for it.</p><button class="secondary" onclick="setMode('aurora')">ENTER SKY</button></div><div class="card"><div class="eyebrow">MOON</div><h3>Quiet</h3><p>Blue night. A slower room for slower thoughts.</p><button class="secondary" onclick="setMode('moon')">ENTER SKY</button></div><div class="card"><div class="eyebrow">ROSE</div><h3>Warmth</h3><p>Pink and amber. Memories that still feel gentle.</p><button class="secondary" onclick="setMode('rose')">ENTER SKY</button></div></div><div class="card" style="margin-top:12px"><div class="eyebrow">MIDNIGHT</div><h3>Depth</h3><p>Electric cyan and deep space. The hidden side of the archive.</p><button class="secondary" onclick="setMode('midnight')">ENTER SKY</button></div>`)}
function finale(){let open=Date.now()>=target;return wrap("Where the Sky Opens","10",`<div class="final"><div class="eyebrow">${open?"03 JULY 2027 · OPEN":"SEALED UNTIL 03 JULY 2027"}</div><h2>${open?"Happy Birthday, Chitra.":"Not yet."}</h2>${open?`<div class="poem"><p>May your mornings find you gently.</p><p>May your nights leave room for stars.</p><p>May you never confuse being needed with being loved.</p><p>May you keep your softness without mistaking it for weakness.</p><p>May laughter find you in ordinary places.</p><p>May the future surprise you kindly.</p></div><p class="long">Chitra, this strange little universe was built around one simple thought: a birthday can be a pause.

A chance to look at what survived, what exists now, and what might still become.

I hope you collect years that feel like rooms with open windows.

I hope you meet people who never make you earn your place beside them.

And when life becomes loud, I hope you remember there is always a quieter sky inside you.

Happy birthday.

The website ends here.

The universe doesn't.</p>`:`<div class="quote">This door is deliberately quiet. On July 3, 2027, it opens by itself.</div>`}</div>`)}
const pages={home,garden,letters,poetry,memory,timeline,signals,dream,observatory,modes,finale};
function render(){let id=location.hash.slice(1)||"home";if(!pages[id])id="home";page.innerHTML=pages[id]();if(id==="garden")initGarden();if(id==="home")tick();}addEventListener("hashchange",render);
function preview(){let p=prompt("Creator preview code");if(p===PASS){sessionStorage.setItem("creator","yes");creator=true;notify("Creator preview unlocked.");document.getElementById("rooms").scrollTop=0;go("garden")}else notify("That code did not open the archive.")}
function tick(){let e=target-Date.now();if(e<0)return;let vals=[Math.floor(e/86400000),Math.floor(e/3600000)%24,Math.floor(e/60000)%60,Math.floor(e/1000)%60];["d","h","m","s"].forEach((x,i)=>{let q=document.getElementById(x);if(q)q.textContent=String(vals[i]).padStart(2,"0")})}setInterval(()=>{if(document.getElementById("d"))tick();if(Date.now()>=target&&!creator&&location.hash==="#home")render()},1000);
function initGarden(){let c=document.getElementById("gc"),x=c.getContext("2d");function size(){c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);draw()}function draw(){x.clearRect(0,0,c.clientWidth,c.clientHeight);let n=+localStorage.garden||0;for(let i=0;i<n;i++){let px=(i*83)%c.clientWidth,py=c.clientHeight-20-(i*31)%(c.clientHeight-45);x.strokeStyle=getComputedStyle(document.body).getPropertyValue("--a");x.beginPath();x.moveTo(px,py);x.lineTo(px+(i%3-1)*14,py-65-(i%4)*10);x.stroke();x.fillStyle=getComputedStyle(document.body).getPropertyValue("--b");x.beginPath();x.arc(px+(i%3-1)*14,py-65-(i%4)*10,4,0,7);x.fill()}}window.plant=()=>{localStorage.garden=(+localStorage.garden||0)+1;update()};window.clearGarden=()=>{localStorage.garden=0;update()};function update(){let n=+localStorage.garden||0;document.getElementById("gb").style.width=Math.min(100,n*4)+"%";document.getElementById("gt").textContent=n?`${n} light${n>1?"s":""} growing · the garden remembers.`:"The soil is waiting.";draw()}addEventListener("resize",size);size();update()}
let sn=0;window.signal=()=>{if(location.hash!=="#signals")return;sn=Math.min(7,sn+1);document.getElementById("sig").textContent=`${sn} / 7 · signal received`;if(sn===7){document.getElementById("secret").style.display="block";notify("The seventh signal arrived.")}};
window.weather=(w)=>{let d={calm:["The room exhales.","Nothing needs to be solved tonight.","A quiet universe is still a universe."],wild:["Be a little unreasonable.","Some joy is supposed to be impractical.","Go where the strange stories are."],hope:["There are unopened mornings.","The story is still moving.","You have not met all your good days yet."],nostalgia:["Keep the warmth.","Release the weight.","The past can be beautiful without becoming a destination."]}[w];document.getElementById("weatherTitle").textContent=d[0];document.getElementById("weatherBody").textContent=d[1];document.getElementById("weatherQuote").textContent=d[2]};
render();

/* independent animated star field */
const sc=document.getElementById("stars"),sx=sc.getContext("2d");let ss=[];function resize(){sc.width=innerWidth*devicePixelRatio;sc.height=innerHeight*devicePixelRatio;sx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ss=Array.from({length:Math.min(230,Math.floor(innerWidth/5))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.2+Math.random()*1.3,v:.03+Math.random()*.18,a:.15+Math.random()*.65}))}function loop(){sx.clearRect(0,0,innerWidth,innerHeight);sx.fillStyle=getComputedStyle(document.body).getPropertyValue("--a");ss.forEach(s=>{s.y+=s.v;if(s.y>innerHeight)s.y=-2;sx.globalAlpha=s.a;sx.beginPath();sx.arc(s.x,s.y,s.r,0,7);sx.fill()});sx.globalAlpha=1;requestAnimationFrame(loop)}addEventListener("resize",resize);resize();loop();